#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
        . /usr/share/dbconfig-common/dpkg/config.pgsql
        if ! dbc_go backle $@ ; then
            echo 'Automatic configuration using dbconfig-common failed!'
        fi
fi

#TODO:
db_version 2.0

db_input low backle/setup-username || true
db_input low backle/setup-password || true

db_go || true

