#!/bin/sh
# postinst script for backle

set -e

apache_install() {
	mkdir -p /etc/apache2/conf-available
	ln -sf ../../backle/apache.conf /etc/apache2/conf-available/backle.conf
	
	COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		apache2_invoke enconf backle
	elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
		[ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/backle.conf ] && ln -s ../conf-available/backle.conf /etc/apache2/conf.d/backle.conf
	fi
}

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.pgsql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/backle/config-db.php

if ! dbc_go backle $@ ; then
	echo 'Automatic configuration using dbconfig-common failed!'
fi

if [ "$1" = "configure" ]; then

        #TODO: What do we need this version for?
	db_version 2.0

	apache_install $1
        /etc/init.d/apache2 reload 3>/dev/null || true

#Don't think we need this, seems to be for choosing the http server
#
#	# Configure Apache
#	db_get backle/reconfigure-webserver
#
#	webservers="$RET"
#
#	for webserver in $webservers; do
#		webserver=${webserver%,}
#		if [ "$webserver" = "lighttpd" ] ; then
#			lighttpd_install
#		else
#			apache_install $1
#		fi
#		# Reload webserver in any case, configuration might have changed
#		# Redirection of 3 is needed because Debconf uses it and it might 
#		# be inherited by webserver. See bug #446324.
#        if [ -f /etc/init.d/$webserver ] ; then
#            if [ -x /usr/sbin/invoke-rc.d ]; then
#                invoke-rc.d $webserver reload 3>/dev/null || true
#            else
#                /etc/init.d/$webserver reload 3>/dev/null || true
#            fi
#        fi
#	done
fi


#DEBHELPER#

exit 0

