#!/bin/sh
# postrm script for backle

set -e

apache_remove() {
        COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
                . /usr/share/apache2/apache2-maintscript-helper
                apache2_invoke disconf backle
        elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
                rm -f /etc/apache2/conf.d/backle.conf
        fi

	rm -f /etc/apache2/conf-available/backle.conf
}
if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgadmin ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.pgadmin
    if ! dbc_go backle $@ ; then
        echo 'Automatic configuration using dbconfig-common failed!'
    fi
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/backle/config-db.php
    if which ucf >/dev/null 2>&1; then
	ucf --debconf-ok --purge /etc/backle/config-db.php
    fi
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

	if [ -f /usr/share/debconf/confmodule ]; then
		db_version 2.0

		apache_remove $1
		invoke-rc.d apache2 reload 3>/dev/null || true

	fi
fi


#DEBHELPER#

exit 0
